import os
import numpy as np

# the shape of input, BHWC, B must be 1 and C must be 3
IMG_SHAPE = [1,736,1280,3]
# the mean value of RGB
IMG_MEAN = np.array([123.68, 116.78, 103.94],dtype=np.float32)
# weight decay used in training
WEIGHT_DECAY = 1E-5
# scale factor
TEXT_SCALE = 512

# get root of project
# The trained tensorflow checkpoint path
CHECKPOINT_PATH = '.'
# The path of prototxt file (all nodes information) generated by RbCompiler
# PROTOTXT_PATH = os.path.join(ROOT,"Rb_tools/EAST_sg.pbtxt")
# The path of prototxt file with opt
PROTOTXT_PATH = '/root/newhome/workspace/myTools/rb_tools/inception_resnet_v2/inception_resnet_v2_sg.pbtxt'
# The path of binary coefficient files generated by RbCompiler
COEFF_DIR = '/root/newhome/workspace/myTools/rb_tools/inception_resnet_v2/inception_resnet_v2_float_coeff/coeff_little'
# The directory of images should be inferred
INFER_IMG_DIR = '/root/newhome/Imagenet/Imagenet-val'
# the output directory of inferred image
OUTPUT_DIR = '.'

OUTPUT_NODE_LIST=[
    'InceptionResnetV2/Logits/Logits/MatMul'
    ]


